library(readr)
EURUSD_mt5_ticks <- read.csv("EURUSD_mt5_ticks.csv",sep=""  )

EURUSD_mt5_ticks=EURUSD_mt5_ticks[c(5000:1000000),]
data=EURUSD_mt5_ticks
dim(data)
head(data)
#data gathering part is completed.




#Volatility regions

# Load necessary libraries
library(dplyr)
library(TTR)  # For ATR calculation



# Convert Date and Timestamp to datetime format
data$Datetime <- as.POSIXct(paste(data$Date, data$Timestamp), format="%Y%m%d %H:%M:%S")

# Calculate the True Range (TR) and ATR
data$TR <- pmax(
  data$High - data$Low, 
  abs(data$High - lag(data$Close, 1, order_by = data$Datetime)),
  abs(data$Low - lag(data$Close, 1, order_by = data$Datetime))
)


# Remove first and last rows from the data
data <- data[-1, ]  # Removes the first row
data <- data[-nrow(data), ]  # Removes the last row

# View the result
head(data)

View(data)

data=na.omit(data)
# Calculate the ATR (14-period by default)
data$ATR <- TTR::SMA(data$TR, n = 14)

data=na.omit(data)



# Remove NAs generated by the lag function or SMA


# K-Means clustering on ATR to classify volatility regimes
set.seed(123)  # For reproducibility
kmeans_result <- kmeans(data$ATR, centers = 3)  # 3 clusters: Low, Medium, High volatility

# Add the volatility regimes to the data
data$Volatility_Regime <- factor(kmeans_result$cluster, labels = c("Low", "Medium", "High"))

# View the result
head(data)
